AP_HAL_F4BY_Namespace.h was removed
dipspb/ardupilot pull request #1
Opened 2017-01-12 11:49 UTC by mstrinzha

2017-01-14 14:57 UTC, dipspb requested changes
Максим, посмотри мои комменты пожалуйста

2017-01-14 14:57 UTC, dipspb commented on libraries/AP_HAL_F4BY/GPIO.h
> +class F4BYDigitalSource : public AP_HAL::DigitalSource {
Максим, а разве ненужно было переименовать F4BYDigitalSource в DigitalSource?

2017-01-14 14:57 UTC, dipspb commented on libraries/AP_HAL_F4BY/I2CDevice.h
> +
Это видимо случайно попало, пустой Tab

2017-01-23 17:22 UTC, mstrinzha commented on libraries/AP_HAL_F4BY/GPIO.h
> +class F4BYDigitalSource : public AP_HAL::DigitalSource {
Сейчас переименую.

2017-01-23 17:22 UTC, mstrinzha commented on libraries/AP_HAL_F4BY/I2CDevice.h
> +
Случайно.

2017-01-23 17:41 UTC, dipspb approved these changes

2017-01-23 17:41 UTC, merged